
alertmanager:
  ingress:
    enabled: true

    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.main.podlipd.online"
      cert-manager.io/cluster-issuer: "letsencrypt-stage"
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
      kubernetes.io/ingress.class: nginx


    ## Hosts must be provided if Ingress is enabled.
    ##
    hosts:
      - alert-manager.main.podlipd.online
      # - alertmanager.domain.com

    ## Paths to use for ingress rules - one path should match the alertmanagerSpec.routePrefix
    ##
    paths:
    - /

    ## TLS configuration for Alertmanager Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
    - secretName: alert-manager-general-tls
      hosts:
      - alert-manager.main.podlipd.online

## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## Annotations for Grafana Ingress
    ##
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.main.podlipd.online"
      cert-manager.io/cluster-issuer: "letsencrypt-stage"
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"


    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts:
      - grafana.main.podlipd.online

    ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.main.podlipd.online


prometheus:

  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.main.podlipd.online"
      cert-manager.io/cluster-issuer: "letsencrypt-stage"
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
      kubernetes.io/ingress.class: nginx
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enabled.
    ##
    # hosts:
    #   - prometheus.domain.com
    hosts:
      - prometheus.main.podlipd.online

    ## Paths to use for ingress rules - one path should match the prometheusSpec.routePrefix
    ##
    paths:
    - /

    ## TLS configuration for Prometheus Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
    - secretName: prometheus-general-tls
      hosts:
      - prometheus.main.podlipd.online
      # - secretName: prometheus-general-tls
      #   hosts:
      #     - prometheus.example.com
