{{- if and .Values.requires_db (not .Values.global.useDBOperator) }}
{{- if (.Values.requires_db|default false) }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-db-external-secret
  labels:
{{ include "app.labels" $ | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback
    "helm.sh/hook-weight": "1"
spec:
  backendType: secretsManager
  data:
  - key: {{ .Values.aws.eksCluster }}-aurora-postgresql-10.7 
    name: db_user
    property: db_user
  - key: {{ .Values.aws.eksCluster }}-aurora-postgresql-10.7 
    name: db_password
    property: db_password
  - key: {{ .Values.aws.eksCluster }}-aurora-postgresql-10.7 
    name: db_host
    property: db_host
{{- end }}
{{- end }}