{{- if .Values.requires_db|default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-access
  labels: {{ include "app.labels" $ | nindent 4 }}
stringData:
  db_password: {{ .Values.db.password }}
type: Opaque
{{- end }}