{{- if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-secrets
  labels: {{ include "app.labels" $ | nindent 4 }}
stringData:
{{- range $key,$val := .Values.env.secrets }}
  {{ $key }}: {{ tpl ($val|toString) $ | quote }}
{{- end }}
type: Opaque
{{- end }}
