{{- if .Values.apigw.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apigw-secret
  labels: {{ include "app.labels.static" $ | nindent 4 }}
  annotations:
    rhsso.cli/client-id: {{ .Release.Name }}
    rhsso.cli/target-instance: {{ .Values.sso.instance }}
    rhsso.cli/target-realm: {{ .Values.sso.realm }}
    apigw.cfg/client-id: {{ .Release.Name }}
stringData:
  secret: {{ .Values.apigw.secret }}
type: Opaque
{{- end }}
