{{- if and .Values.requires_db .Values.global.useDBOperator }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Chart.Name }}-db-operator-data
  annotations:
  {{-  if or (and .Values.db.recreate .Values.db.recreate_status) .Values.db.recreate_force }}
    db.operator.postgresql/recreate_db_trigger: {{ randAlphaNum 64 }}
  {{- end }}
    db.operator.postgresql/database: {{ include "app.db_host" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }}
type: Opaque
stringData:
  target_user: {{ include "app.db_username" $ }}
  target_user_role: CREATEDB
  target_user_password: {{ .Values.db.password }}
  target_db_name: {{ include "app.db_name" $ }}
  target_extensions: {{ .Values.db.extensions | quote}}
{{- end }}
