apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-exporter
  namespace: monitoring
  labels:
    app: aws-cost-exporter
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::557064355951:role/prometheus_aws_cost_exporter_role'
  selfLink: /api/v1/namespaces/cert-manager/serviceaccounts/cert-manager
