apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-tool
  labels:
    app: net-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-tool
  template:
    metadata:
      labels:
        app: net-tool
    spec:
      containers:
      - name: net-tool
        image: praqma/network-multitool
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: net-tool
  labels:
    app: net-tool
spec:
  ports:
  - port: 80
  selector:
    app: net-tool
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.main.podlipd.online"
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
spec:
  tls:
  - hosts:
    - net-tool.main.podlipd.online
    secretName: net-tool-tls
  rules:
  - host: "net-tool.main.podlipd.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: net-tool
            port:
              number: 80
  ingressClassName: nginx
